index:
    path: /
    controller: App\Controller\LearningController::index

aboutMe:
    path: about-me
    controller: App\Controller\LearningController::aboutMe

form:
    path: form
    controller: App\Controller\LearningController::showName

showName:
    path: showName
    controller: App\Controller\LearningController::changeName
